name: rickmorty
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.5
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  get: 4.6.6
  google_fonts: ^6.1.0
  url_launcher: ^6.2.3

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/icon-launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
